-- Add user profile columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS residence TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS workplace TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS transport_go TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS transport_go_cost NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS transport_return TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS transport_return_cost NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS meals_per_day NUMERIC DEFAULT 3;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cost_per_meal NUMERIC DEFAULT 0;
